spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      server:
        webflux:
          routes:
            - id: userservice
              uri: lb://USERSERVICE
              predicates:
                - Path=/users/**


            - id: profileservice
              uri: lb://PROFILESERVICE
              predicates:
                - Path=/profiles/**


            - id: authservice
              uri: lb://AUTHSERVICE
              predicates:
                - Path=/auth/**


            - id: jobservice
              uri: lb://JOBSERVICE
              predicates:
                - Path=/jobs/**


            - id: notificationservice
              uri: lb://NOTIFICATIONSERVICE
              predicates:
                - Path=/notification/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true


server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
