spring:

  config:
    import: optional:notificationservice.secret.yml

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: job-portal-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.nextrole.*"   # ✅ safer than "*"
        # spring.json.value.default.type: com.nextrole.common_dto.dto.UserCreatedEvent


    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false  



server:
  port: 8085


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
