server:
  port: 8081

spring:
  application:
    name: userservice
  
  config:
    import: optional:user-service.secret.yml

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect