spring:
  application:
    name: authservice

  config:
    import: optional:auth-service.secret.yml

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false   

server:
  port: 8083


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
